import csv
import math

csvFile = open("c2.csv", "r")
reader = csv.reader(csvFile)
gen3 = math.sqrt(3)

with open('cylinder2.txt','w') as wf:
    wf.write('mtllib cylinder.mtl'+'\n')
    wf.write('g default'+'\n')
    # with open('cylinder.txt','r') as f:
        # for line in f.readlines():
    for line in reader:
        # wf.write(str(line))
        # print(line[0])
        x = int(line[0])
        y = int(line[1])
        z = line[2]
        r = int(line[3])
        wf.write('v'+' '+str(x)+' '+str(y)+' '+z+'\n')
        wf.write('v'+' '+str(x-r/2)+' '+str(y+r/2*gen3)+' '+z+'\n')
        wf.write('v'+' '+str(x-r)+' '+str(y)+' '+z+'\n')
        wf.write('v'+' '+str(x-r/2)+' '+str(y-r/2*gen3)+' '+z+'\n')
        wf.write('v'+' '+str(x+r/2)+' '+str(y-r/2*gen3)+' '+z+'\n')
        wf.write('v'+' '+str(x+r)+' '+str(y)+' '+z+'\n')
        wf.write('v'+' '+str(x+r/2)+' '+str(y+r/2*gen3)+' '+z+'\n')
    wf.write('\n')
    wf.write('s1'+'\n')
    wf.write('g pCylinder1'+'\n')
    wf.write('usemtl file1SG'+'\n')
    wf.write('f 1 2 3'+'\n')
    wf.write('f 3 4 1'+'\n')
    wf.write('f 1 4 5'+'\n')
    wf.write('f 5 6 1'+'\n')
    wf.write('f 1 6 7'+'\n')
    wf.write('f 7 2 1'+'\n')
    wf.write('s2'+'\n')
    wf.write('f 3 10 4'+'\n')
    wf.write('f 4 10 11'+'\n')
    wf.write('s3'+'\n')
    wf.write('f 2 9 3'+'\n')
    wf.write('f 3 9 10'+'\n')
    wf.write('s4'+'\n')
    wf.write('f 7 14 2'+'\n')
    wf.write('f 2 14 9'+'\n')
    wf.write('s5'+'\n')
    wf.write('f 6 13 7'+'\n')
    wf.write('f 7 13 14'+'\n')
    wf.write('s6'+'\n')
    wf.write('f 5 12 6'+'\n')
    wf.write('f 6 12 13'+'\n')
    wf.write('s7'+'\n')
    wf.write('f 4 11 5'+'\n')
    wf.write('f 5 11 12'+'\n')
    wf.write('s8'+'\n')
    wf.write('f 8 9 10'+'\n')
    wf.write('f 10 11 8'+'\n')
    wf.write('f 8 11 12'+'\n')
    wf.write('f 12 13 8'+'\n')
    wf.write('f 8 13 14'+'\n')
    wf.write('f 14 9 8'+'\n')
csvFile.close()


